version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
      - netbsd
    goarch:
      - amd64
      - arm64
      - "386"

  - id: android
    binary: gh-s
    env:
      - CGO_ENABLED=0
      - GODEBUG=netdns=go
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - android
    goarch:
      - arm64

archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    formats: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github-native

