version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
      - android
      - netbsd
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: android
        goarch: amd64
      - goos: android
        goarch: "386"

archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    formats: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github-native

